INSERT INTO projects(title) VALUES ('Animal shelter needs dog food');
INSERT INTO projects(title) VALUES ('Help me buy a guitar');
INSERT INTO projects(title) VALUES ('Help save birds of paradise');
INSERT INTO projects(title) VALUES ('I have bed bugs!');
INSERT INTO projects(title) VALUES ('I want to teach English in China');
INSERT INTO projects(title) VALUES ('Iguana needs tail operation');
INSERT INTO projects(title) VALUES ('My book on SQL');
INSERT INTO projects(title) VALUES ('The next Harry Potter');
INSERT INTO projects(title) VALUES ('The next Inna-Gadda-Davida');
INSERT INTO projects(title) VALUES ('Voldemort needs a body');


INSERT INTO users(name) VALUES ('Harry Potter');
INSERT INTO users(name) VALUES ('Ron Weasley');
INSERT INTO users(name) VALUES ('Hermione Granger');
INSERT INTO users(name) VALUES ('Fred Weasley');
INSERT INTO users(name) VALUES ('George Weasley');
INSERT INTO users(name) VALUES ('Severus Snape');
INSERT INTO users(name) VALUES ('Albus Dumbledore');
INSERT INTO users(name) VALUES ('Hagrid');
INSERT INTO users(name) VALUES ('Draco Malfoy');
INSERT INTO users(name) VALUES ('Neville Longbottom');
INSERT INTO users(name) VALUES ('Sirius Black');
INSERT INTO users(name) VALUES ('Remus Lupin');
INSERT INTO users(name) VALUES ('James Potter');
INSERT INTO users(name) VALUES ('Lily Potter');
INSERT INTO users(name) VALUES ('Minerva McGonagall');
INSERT INTO users(name) VALUES ('Voldemort');
INSERT INTO users(name) VALUES ('Arthur Weasley');
INSERT INTO users(name) VALUES ('Molly Weasley');
INSERT INTO users(name) VALUES ('Bellatrix Lestrange');
INSERT INTO users(name) VALUES ('Dobby');

INSERT INTO pledges(amount) VALUES (210);
INSERT INTO pledges(amount) VALUES (98);
INSERT INTO pledges(amount) VALUES (170);
INSERT INTO pledges(amount) VALUES (200);
INSERT INTO pledges(amount) VALUES (1035.5);
INSERT INTO pledges(amount) VALUES (20);
INSERT INTO pledges(amount) VALUES (120);
INSERT INTO pledges(amount) VALUES (342);
INSERT INTO pledges(amount) VALUES (489);
INSERT INTO pledges(amount) VALUES (10);
INSERT INTO pledges(amount) VALUES (11);
INSERT INTO pledges(amount) VALUES (12);
INSERT INTO pledges(amount) VALUES (13);
INSERT INTO pledges(amount) VALUES (14);
INSERT INTO pledges(amount) VALUES (15);
INSERT INTO pledges(amount) VALUES (16);
INSERT INTO pledges(amount) VALUES (17);
INSERT INTO pledges(amount) VALUES (18);
INSERT INTO pledges(amount) VALUES (19);
INSERT INTO pledges(amount) VALUES (20);
INSERT INTO pledges(amount) VALUES (21);
INSERT INTO pledges(amount) VALUES (22);
INSERT INTO pledges(amount) VALUES (23);
INSERT INTO pledges(amount) VALUES (24);
INSERT INTO pledges(amount) VALUES (25);
INSERT INTO pledges(amount) VALUES (26);
INSERT INTO pledges(amount) VALUES (27);
INSERT INTO pledges(amount) VALUES (28);
INSERT INTO pledges(amount) VALUES (29);
INSERT INTO pledges(amount) VALUES (30);
